---
- name: Deploy Flask App on WSL2
  hosts: localhost
  become: true
  tasks:
    - name: Ensure unzip is installed (fixes earlier bug)
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask and SQLite3
      shell: |
        python3 -m pip install flask --break-system-packages
        apt install -y sqlite3
      args:
        executable: /bin/bash

    - name: Copy application files
      copy:
        src: src/
        dest: /home/rohan/flaskapp/
        mode: '0755'

    - name: Run Flask App with nohup
      shell: |
        nohup python3 /home/rohan/flaskapp/main.py > /home/rohan/flaskapp/app.log 2>&1 &
      args:
        executable: /bin/bash
