---
- name: Deploy Flask App on WSL2
  hosts: all
  become: true
  tasks:

    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask using apt to avoid pip errors
      apt:
        name: python3-flask
        state: present
    
    - name: Install SQLite3
      apt:
        name: sqlite3
        state: present

    - name: Copy Flask application files
      copy:
        src: ../app/
        dest: /home/rohan/flaskapp/
        mode: preserve
      vars:
        ansible_become: true

    - name: Run Flask App in background using nohup (instead of systemd)
      shell: |
        nohup python3 /home/rohan/flaskapp/main.py > /home/rohan/flaskapp/flask.log 2>&1 &
      args:
        executable: /bin/bash
