---
- name: Deploy Flask App on WSL2
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Flask using pip3
      pip:
        name: flask
        executable: pip3

    - name: Install SQLite3
      apt:
        name: sqlite3
        state: present

    - name: Create app directory
      file:
        path: /home/rohan/flaskapp
        state: directory
        mode: '0755'

    - name: Copy Flask app files
      copy:
        src: ../app/
        dest: /home/rohan/flaskapp/
        mode: '0755'

    - name: Start Flask app in background (no systemd)
      shell: |
        nohup python3 /home/rohan/flaskapp/main.py > /home/rohan/flaskapp/flask.log 2>&1 &
      args:
        executable: /bin/bash
