---
- name: Deploy Flask App on WSL2
  hosts: flask_wsl
  become: true
  tasks:
    - name: Ensure unzip is installed (fixes earlier bug)
      apt:
        name: unzip
        state: present

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask and SQLite3
      pip:
        name:
          - flask

    - name: Create app directory
      file:
        path: /home/runner/flask-app
        state: directory

    - name: Copy application files
      copy:
        src: ../..
        dest: /home/runner/flask-app/
        remote_src: no

    - name: Kill old Flask app if any
      shell: pkill -f "main.py" || true

    - name: Run Flask app with nohup
      shell: |
        cd /home/runner/flask-app/app
        nohup python3 main.py > flask.log 2>&1 &
