name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip install ansible

    - name: Archive Flask App
      run: |
        zip -r flask-app.zip . -x '*.git*' '*venv*'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flask-app
        path: flask-app.zip

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
