name: CD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Deployment Message
      run: |
        echo "🚀 Starting Deployment..."
        echo "Deployed at $(date)" > deploy-log.txt

    - name: Upload Deployment Log
      uses: actions/upload-artifact@v4
      with:
        name: deploy-log
        path: deploy-log.txt
