name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.10 and dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.10 python3.10-venv python3.10-dev python3-pip zip

      - name: Set up Python virtual environment
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests

      - name: Archive Flask App
        run: |
          zip -r flask-app.zip . -x "*venv*" "*.git*" "*.github*" "*.vagrant*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-app
          path: flask-app.zip

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
